"""``carb3/data/reference_mvp/`` solves the three premises exactly as the full tables do.

The subset is generated by ``carb3/data/build_reference_mvp.py``. Its filtering rule is a
closure argued from the loader, so the only proof it dropped nothing the model reads is to
solve both ways and compare every ledger table.

Three things legitimately differ and are excluded, nothing else: ``wall_clock_seconds``, the
two counts that cover the §3.2 admission screen (it screens every unit in the root it is
given, and the subset holds fewer), and ``screen_dropped.parquet``, which must be a subset of
the full run's drop list rather than equal to it.
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

import pandas as pd
import pytest

from carb3.__main__ import main
from carb3.load import REFERENCE_SCHEMA

#: Columns of ``run_report`` that depend on the size of the root or on the clock.
SCREEN_AND_CLOCK = ("wall_clock_seconds", "n_units_admitted", "n_units_dropped")


@pytest.fixture(scope="module")
def generator(repo_root: Path):
    path = repo_root / "carb3" / "data" / "build_reference_mvp.py"
    spec = importlib.util.spec_from_file_location("build_reference_mvp", path)
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def test_generator_covers_every_reference_table(generator) -> None:
    assert tuple(generator.TABLES) == tuple(REFERENCE_SCHEMA)


def test_committed_subset_is_current(generator) -> None:
    assert generator.main(["--check"]) == 0


@pytest.fixture(scope="module")
def runs(repo_root: Path, tmp_path_factory) -> tuple[Path, Path]:
    full = tmp_path_factory.mktemp("full")
    subset = tmp_path_factory.mktemp("subset")
    assert main(["--out-dir", str(full), "--no-report"]) == 0
    status = main(
        [
            "--reference-root", str(repo_root / "carb3" / "data" / "reference_mvp"),
            "--out-dir", str(subset), "--no-report",
        ]
    )
    assert status == 0
    return full, subset


def test_ledgers_match_on_the_subset(runs: tuple[Path, Path]) -> None:
    full, subset = runs
    files = sorted(p.relative_to(full) for p in full.rglob("*.parquet"))
    assert files, "no ledger tables written"
    for rel in files:
        a, b = pd.read_parquet(full / rel), pd.read_parquet(subset / rel)
        if rel.name == "screen_dropped.parquet":
            assert set(map(tuple, b.astype(str).values)) <= set(map(tuple, a.astype(str).values))
            continue
        if rel.name == "run_report.parquet":
            a, b = a.drop(columns=list(SCREEN_AND_CLOCK)), b.drop(columns=list(SCREEN_AND_CLOCK))
        pd.testing.assert_frame_equal(a, b, obj=str(rel))
